version: '3.8'

services:
  deepthought-frontend:
    image: deepthought-frontend:latest
    build: 
        context: frontend
        dockerfile: Dockerfile
    container_name: deepthought-frontend
    ports:
      - '80:80'
    networks:
      -deepthoughtNet


  deepthought-backend:
    image: 'deepthought-backend:latest'
    build:
        context: backend
        dockerfile: Dockerfile
    container_name: deepthought-backend
    depends_on:
       deepthought-database:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://deepthought-db:5432/deepthought_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
    ports:
      - 8080:8080
    networks:
      -deepthoughtNet


  deepthought-database:
    image: 'postgres:15'
    container_name: deepthought-db
    environment:
      - POSTGRES_DB=teambuilder_db
      - POSTGRES_USER=postgres
      - PGUSER=postgres
      - POSTGRES_PASSWORD=admin
      - PGDATA=/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "--quiet"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data/:rw
    networks:
      -deepthoughtNet


networks:
deepthoughtNet :
    name: deepthoughtNet
    driver: bridge

    
volumes:
  postgres_data: