server:
  port : 8080

spring:
  datasource:
    url : jdbc:postgresql://localhost:5432/deepthought_db
    username : postgres
    password : admin

  jpa:
    generate-ddl : true
    hibernate :
      ddl-auto : validate
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  output:
    ansi:
      enabled : always

springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

javamelody:
  enabled: true
  spring-monitoring-enabled: true
  init-parameters:
    log: true