server:
  port : 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url : jdbc:postgresql://localhost:5432/deepthought_db
    username : postgres
    password : admin

  jpa:
    generate-ddl : true
    hibernate :
      ddl-auto : validate
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  output:
    ansi:
      enabled : always

springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.html